$:.unshift File.dirname(__FILE__)

# Vendor
require 'rubygems'
require 'zip/zip'
require 'zip/zipfilesystem'
require 'active_support'
require 'sanitize'
require 'fastimage'
require 'fileutils'
require 'uri'
require 'cgi'
require 'pathname'
require 'tmpdir'
require 'mime/types'
require 'digest/md5'
require 'pathname'
require 'date'
require 'html_compressor'
require "yui/compressor"
require "sass"
require 'sass/css'
require 'tempfile'

# Tools
require 'epub/tools/dom'
require 'epub/tools/file_system'
require 'epub/tools/identifier'
require 'epub/tools/path_manipulation'
require 'epub/tools/xml'
require 'epub/tools/zip_file'

# Epub
require 'epub/document'
require 'epub/opf'
require 'epub/opf/guide'
require 'epub/opf/manifest'
require 'epub/opf/metadata'
require 'epub/opf/spine'
require 'epub/item'
require 'epub/item/html'
require 'epub/item/html/html_link'
require 'epub/item/css'
require 'epub/item/css/sass_line'
require 'epub/item/image'
require 'epub/item/toc'
require 'epub/item/toc/toc_element'
require 'epub/version'